name: Build and Push Docker Image
on:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login into ACR
        if: ${{ github.ref == 'refs/heads/main' }}
        run: az acr login --name ${{ vars.REGISTRY }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ vars.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ inputs.TAG }}
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app/src
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
