name: Build and Push
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  workflow_dispatch:

env:
  REGISTRY: acrraalbums.azurecr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login into ACR
        if: ${{ github.ref == 'refs/heads/main' }}
        run: az acr login --name ${{ env.REGISTRY }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app/src
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
