name: CI/CD Workflow

on:
  pull_request:
    branches: 
      - main
    paths: 
      - 'app/**'

  push:
    branches:
      - main
    paths: 
      - 'app/**'
  
  release:
    types:
      - published

defaults:
  run:
    working-directory: app/src

env:
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

  build:
    name: Build and push docker image
    needs:
      - ci
    uses: ./.github/workflows/build-and-push.yaml
    permissions:
      contents: read
    secrets: inherit
    with:
      TAG: ${{ github.event.release.tag_name || github.sha }}
  
  terraform:
    name: Terraform Plan
    needs: 
      - build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Generate Plan
        run: terraform plan -var-file="./environments/${{ github.event_name == 'release' && 'prod' || 'dev' }}.tfvars" -var="image_tag=${{ github.event.release.tag_name || github.sha }}" -out=tfplan

      - name: Save Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.event_name == 'release' && 'prod' || 'dev' }}
          path: infra/terraform/tfplan
          retention-days: 1 
          overwrite: true

  deploy:
    name: Deploy application
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}
    needs: 
      - terraform
    uses: ./.github/workflows/deploy.yaml
    permissions:
      contents: read
    secrets: inherit
    with:
      ENVIRONMENT: ${{ github.event_name == 'release' && 'prod' || 'dev' }}
      TAG: ${{ github.event.release.tag_name || github.sha }}
      PLAN_ARTIFACT_NAME: ${{ format('tfplan-{0}', (github.event_name == 'release' && 'prod' || 'dev')) }}
      
    